language: scala
sudo: required
jdk:
- openjdk8
scala:
- 2.11.7
services:
- docker
script:
- sbt compile coverage test scapegoat check coverageReport copyCoverage makeSite

before_install:
- openssl aes-256-cbc -K $encrypted_a0e0047aef74_key -iv $encrypted_a0e0047aef74_iv
  -in ghpages_ecdsa.enc -out ~\/.ssh/ -d

after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && sbt ghpagesPushSite
notifications:
  email:
  - allixender@googlemail.com
