apiVersion: v1
kind: Service
metadata:
  annotations:
    notes: "cswingester dev instance play http endpoint, proxied via HTTP from NGinx Central"
  labels:
    app: cswingester
    environment: development
  name: cswingester-dev
  namespace: default
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: cswingester
    environment: development
---
apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    software: "Play Framework 2.5.x"
    notes: "uses in memory RAMDirectory index"
  labels:
    app: cswingester
    environment: development
  name: cswingester-dev
  namespace: default
spec:
  replicas: 1
  selector:
    app: cswingester
    environment: development
  template:
    metadata:
      annotations:
        software: "Play Framework 2.5.x"
        notes: "uses in memory RAMDirectory index"
      labels:
        app: cswingester
        environment: development
    spec:
      containers:
      - image: eu.gcr.io/dynamic-cove-129211/cswingester:150
        imagePullPolicy: Always
        name: cswingester-dev
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 300m
            memory: 1280Mi
          requests:
            cpu: 150m
            memory: 768Mi
        env:
        - name: JAVA_OPTS
          value: -Xmx1216M
        - name: APPLICATION_SECRET
          valueFrom:
            secretKeyRef:
              key: appsecret
              name: play-crypto
        - name: INDEX_CACHE_DIR
          value: /mnt/data
        volumeMounts:
        - mountPath: /mnt/data
          name: index-cache-vol
      restartPolicy: Always
      volumes:
      - emptyDir:
        name: index-cache-vol
